# Tell Travis we need super user permission to execute the docker build for testing
language: generic
sudo: required
# Travis CLi will install docker to build and run image
service:
  - docker

# Step before test or deployment, we get back id of image after build, we need to tag it
# tag a name to an id, we can use any tag since it's only meant for travis to use
before_install:
  - docker build -t hquach729/docker-react -f Dockerfile.dev .

# Travis assume this run and exit, however our npm test doesn't run and end
script:
  - docker run -e CI=true hquach729/docker-react npm run test
