# Tell Travis we need super user permission to execute the docker build for testing
language: generic
sudo: required
# Travis CLi will install docker to build and run image
service:
  - docker

# Step before test or deployment, we get back id of image after build, we need to tag it
# tag a name to an id, we can use any tag since it's only meant for travis to use
before_install:
  - docker build -t hquach729/docker-react -f Dockerfile.dev .

# Travis assume this run and exit, however our npm test doesn't run and end
script:
  - docker run -e CI=true hquach729/docker-react npm run test

# Tell travis ci to deploy it to elasticbeanstalk
# http://dockerreact-env.eba-mggqgshp.us-east-2.elasticbeanstalk.com/
# Travis will take file from git huba, buck_name is the harddrive, where travis will put a zip file
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-764916343187'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
