# Docker file for development
# Setup Base OS image: Our frontend react service
# A docker file is the instruction on how to create an image for our
# docker container and with instruction on how to start it from docker
# Docker file is basicallly and instruction to create an image

FROM node:alpine

# Setup an app directory that has our frontend files and folder 
WORKDIR '/app'

# Copy our frontend package.json to the WORKDIR
COPY package.json . 

# Install Dependencies from the copy package.json in the WORKDIR
RUN npm install

# Copy everything from our project directories
# We don't need to copy file here to our container since we referce are app direction from container back to our local file
# But is still good to use it
COPY . .



# START React App
CMD [ "npm", "run", "start" ]

